### ISSUE TITLE
iterate through a list of text files in CLI?

### ISSUE THREAD

**Issue by wjz0811** [finnp/node-genderize#2]
Hello Finn and other members of this Team:

thank you very much for sharing your helpful wrapper.

i like it a lot and have no issue. so i hope i can still post my question here... which is how i may iterate the .stream method of this wrapper through a set of text files of names? as in, to run this line

"genderize --country_id=de < .../orig/de.txt > .../output/de.txt"

for 220 input files created for different countries, may i create a loop in the terminal where only the string "de" changes in each iteration? 

i have created these files to be able to run the code with the "country_id" parameter. now i hope to learn to automate the process of feeding in these files, but i do not have a structure in my mind about how. i wonder if any of you would mind giving some direction on trying this?

Viele Grüße
Jinzhao

**Comment by finnp** [comment]
Hello Jinzhao,

are you familiar with bash or javascript?

If you want to do it in bash, you could loop through the files like this. You only would need to figure out how to get the langauge identifier of `$f`:

``` sh
for f in *.txt; do genderize < $f > output/$f; done
```

If you are more familiar with javascript, you could try to write your own node script, which lists the file in a folder and then run each file through a stream (https://github.com/finnp/node-genderize#stream).

Does this help you as a starting point?

By the way, our next NodeSchool is next Monday: https://ti.to/nodeschool-berlin/7

Best,
Finn

**Comment by finnp** [comment]
@wjz0811 Can you share how you did it in the end here? :)

**Comment by wjz0811** [comment]
ah yes. thank You and Johann for your help.

first i renamed the files so that they are without extension. then using your starting point above, i ran the following:

for f in *; do node ~/node_modules/genderize/cli.js --country_id=$f < $f > output/$f.json; done

**Comment by finnp** [comment]
Okay, that's pretty cool :)

**Comment by finnp** [comment]
By the way. You can also do  `genderize --language_id languageid --api_key yourapikey` instead of modifying the source code. :)
