### ISSUE TITLE
[QUESTION] Is project maintained?

### ISSUE THREAD

**Issue by motss** [finnp/node-genderize#5]
I come across the public API `genderize` from [toddmotto/public-apis](https://github.com/toddmotto/public-apis/pull/320) and would like to know if this repo still being maintaining since the last update was 5 months ago. It'd be nice if I can help out in contribution 😄 .

**Comment by finnp** [comment]
Hey ☺️  well this is basically a low maintenance project, it should work as it is and will probably not break as long as the API stays the same.

However if you think there are features missing, feel free to create an issue and maybe create a pull request :)
