### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Vandivier** [finnp/node-genderize#6]
[repro here](https://github.com/Vandivier/data-science-practice/tree/genderize-err-repro), just install & `npm start`.

![image](https://user-images.githubusercontent.com/5559355/35185163-d45f7d80-fdcd-11e7-9851-6dd2b71d486f.png)

**Comment by finnp** [comment]
Hey,

I think it might have been that the genderize API was not available. I added a patch to make the error handling better. Let me know if you still have troubled after updating to 1.6.0.

Best,
Finn
